Prevent blank username and invalid password
CSE112-SP22-TeamXRefactor/CSE112-SP22-TeamXRefactor pull request #36
Opened 2022-05-07 23:30 UTC by Sasha45

Forbid empty usernames
Forbid usernames under two characters
Forbid usernames with non-word characters
Forbid PINs under 4 characters
Forbid PINs with non-numeric characters

2022-05-07 23:32 UTC, Sasha45 commented
I expect merge conflicts with #34 :(    Whichever one gets approved second will have to resolve those.

2022-05-09 04:45 UTC, AlejandroM2000 submitted a review, later dismissed

2022-05-11 07:16 UTC, k9kathyli requested changes

2022-05-11 07:16 UTC, k9kathyli commented on source/tests/PuppTests.test.js
> +    it('LoginTest1: no username', async () => {
nit: make test names more descriptive of what they're doing

2022-05-11 07:17 UTC, k9kathyli commented
- [x] Straightforward implementation
- [x] Good design
- [x] Code looks correct
- [x] UI looks as intended and fits guidelines
- [] Adequate test coverage
- [x] Follows coding conventions 
- [] Code is commented/documented well

2022-05-11 07:43 UTC, Sasha45 commented on source/tests/PuppTests.test.js
> +    //Login tests
![image](https://user-images.githubusercontent.com/9505522/167795756-c4a08233-b233-4413-b23f-bbd7a3975904.png)

2022-05-11 07:45 UTC, Sasha45 commented
Proof of passing tests
![image](https://user-images.githubusercontent.com/9505522/167796189-941100c5-5a85-4f84-8d1c-dc3d31d176c1.png)

2022-05-11 18:01 UTC, k9kathyli approved these changes

2022-05-13 02:37 UTC, AlejandroM2000 approved these changes

2022-05-13 19:54 UTC, merged