Login UI improv liu wu
CSE112-SP22-TeamXRefactor/CSE112-SP22-TeamXRefactor pull request #40
Opened 2022-05-09 07:08 UTC by WeMWish

2022-05-09 23:46 UTC, Dsuzuki126 commented
A few things:
1) I recommend you guys write jest tests as manually testing is difficult and I dont think you wrote any (but if you did please show me where)
2) the password reset doesnt have any effect unless I copy and paste the url for the login page into another tab. Refreshing the page and clearing the cache doesn't work. 
3) when I click the "confirm" button there is still a prompt that says incorrect password 
4) the indexDB information doesnt reflect the change in real time hence having to go to another tab
5) small thing, in LoginJS.js on line 98 there is a 'g' missing in the console.log that may cause issues

2022-05-09 23:52 UTC, Dsuzuki126 commented
Another thing I discovered is that if I copy paste the url to another tab then go to a previous tab that I reset the password with and hard refresh the page then I can use the new PIN but the indexDB information is still wrong on the previous tab

2022-05-09 23:56 UTC, Dsuzuki126 requested changes
A few things:
Thanks for removing the unnecessary Login alert
- I recommend you guys write jest tests as manually testing is difficult and I dont think you wrote any (but if you did please show me where); i think if you ran through the functionality you can find different errors that come up
- The password reset doesnt have any effect unless I copy and paste the url for the login page into another tab. Refreshing the page and clearing the cache doesn't work.
- when I click the "confirm" button there is still a prompt that says incorrect password
- the indexDB information doesnt reflect the change in real time hence having to go to another tab
- small thing, in LoginJS.js on line 98 there is a 'g' missing in the console.log that may cause issues
- the way you have implemented the password reset also makes it possible for a user to reset their password PIN to an empty string
- Another thing I discovered is that if I copy paste the url to another tab then go to a previous tab that I reset the password with and hard refresh the page then I can use the new PIN but the indexDB information is still wrong on the previous tab

2022-05-10 02:57 UTC, WeMWish commented
- reset button is now fixed
- the incorrect password message is gone now when clicking confirm button
- line 98, console.log fixed
- the check password functionality is handled by other developers, and since the original code does include this functionality, we decided to leave it
- indexedDB should change dynamically now
- I added a jest test, but it fail to select the reset-password button on the login page. Since learning the jest test takes longer time than I expected and the buttons' functionality is pretty intuitive, to avoid affecting the next iteration, I would leave the test for now.

2022-05-10 17:55 UTC, Dsuzuki126 commented
Thanks for making the changes. 
I apologize as I think some of the indexDB not updating realtime may have been on my side.
There is one thing I am still worried about is that you can still click reset PIN and confirm with no PIN inputted so they could be entering the site with a PIN of empty string so maybe if you could check to make sure that the PIN isn't empty

2022-05-10 23:57 UTC, WeMWish commented
the check for empty password functionality is updated. Thanks for the review!

2022-05-11 03:59 UTC, Dsuzuki126 commented
Noice I think its good now. Thanks guys

2022-05-11 03:59 UTC, Dsuzuki126 approved these changes

2022-05-11 07:28 UTC, k9kathyli requested changes
- [x] Straightforward implementation
- [x] Good design
- [x] Code looks correct
- [x] UI looks as intended and fits guidelines
- [ ] Adequate test coverage
- [x] Follows coding conventions 
- [ ] Code is commented/documented well
Please test locally and upload proof as discussed in Slack.

2022-05-11 07:28 UTC, k9kathyli commented on package-lock.json
> +      "name": "cse110-sp21-group12",
what are the changes in is this file for?

2022-05-11 07:28 UTC, k9kathyli commented on source/Login/LoginJS.js
> + */
weird commenting here

2022-05-11 07:28 UTC, k9kathyli commented on source/Login/LoginJS.js
> +                // loginButton.addEventListener('click', handleLoginButton);
Commented code needed? If not, remove

2022-05-11 07:28 UTC, k9kathyli commented on source/tests/PuppTests.test.js
> +            'https://cse110-sp21-group12.github.io/cse110-sp21-group12/source/Index/Index.html'
wrong url

2022-05-11 07:28 UTC, k9kathyli commented on source/tests/PuppTests.test.js
> +            'https://cse110-sp21-group12.github.io/cse110-sp21-group12/source/Login/Login.html'
wrong url

2022-05-16 03:48 UTC, WeMWish commented
fix puppet test, style issue fixed

2022-05-16 22:08 UTC, PatriciaWuu commented
I also removed all commented code as resolve #15 in this branch to wait for PR

2022-05-16 22:25 UTC, PatriciaWuu commented
<img width="391" alt="Screen Shot 2022-05-15 at 20 10 10" src="https://user-images.githubusercontent.com/49573110/168692295-05d19520-9892-4062-ab10-1357b76b1e87.png">

2022-05-16 22:48 UTC, PatriciaWuu commented
<img width="677" alt="Screen Shot 2022-05-16 at 15 48 47" src="https://user-images.githubusercontent.com/49573110/168694753-c0aaa546-35cf-459d-bc59-2dd803f3ead5.png">

2022-05-25 02:54 UTC, Dsuzuki126 requested changes
make sure you pull all the changes from the main branch;

2022-05-26 23:31 UTC, Dsuzuki126 commented
just a reminder that after pulling from main, you may have conflicts and need to choose which code to use.  Make sure to resolve all change conflicts. It seems like the pupptests.test.js file some of your code mixed with the main branch code

2022-05-31 05:03 UTC, Dsuzuki126 requested changes
just a reminder that after pulling from main, you may have conflicts and need to choose which code to use. Make sure to resolve all change conflicts. It seems like the pupptests.test.js file some of your code mixed with the main branch code

- [x] Straightforward implementation
- [ ] Good design
- [ ] Code looks correct
- [ ] UI looks as intended and fits guidelines
- [x] Adequate test coverage
- [x]  Follows coding conventions
- [x] Code is commented/documented well

2022-05-31 05:03 UTC, Dsuzuki126 commented on source/DailyOverview/DailyOverview.html
> -                </a>
You may need to pull from main as I think someone maybe Hunter, changed the code so there isn't CSS with the HTML which you branch still has

2022-05-31 05:03 UTC, Dsuzuki126 commented on source/MonthlyOverview/MonthlyOverview.html
> +                        id="back"
You may need to pull from main as I think someone maybe Hunter, changed the code so there isn't CSS with the HTML which you branch still has

2022-05-31 05:03 UTC, Dsuzuki126 commented on source/YearlyOverview/YearlyOverview.html
> +                    id="back"
You may need to pull from main as I think someone maybe Hunter, changed the code so there isn't CSS with the HTML which you branch still has

2022-06-02 05:20 UTC, PatriciaWuu approved these changes
resolved

2022-06-03 01:13 UTC, Dsuzuki126 requested changes
- [ ] Straightforward implementation
- [ ] Good design
- [ ] Code looks correct
- [ ] UI looks as intended and fits guidelines
- [ ] Adequate test coverage
- [x] Follows coding conventions
- [ ] Code is commented/documented well

2022-06-03 01:13 UTC, Dsuzuki126 commented on source/tests/PuppTests.test.js
> -    it('Test1: Initial Home Page - Shows create your login ', async () => {
I tried running the Puppeteer tests with your code and it failed a lot so maybe you can take time to figure out what is going on or just send a screenshot that it works on your machine
![image](https://user-images.githubusercontent.com/76570554/171767834-bce60cfe-8454-40ae-86e3-d4b24be1efc3.png)

2022-06-03 19:10 UTC, Dsuzuki126 approved these changes

2022-06-03 19:11 UTC, Dsuzuki126 approved these changes
I ran the tests on my computer and they all passed. Just make sure they pass for you guys.
- [x] Straightforward implementation
- [ ] Good design
- [ ] Code looks correct
- [ ] UI looks as intended and fits guidelines
- [ ] Adequate test coverage
- [ ] Follows coding conventions
- [ ] Code is commented/documented well

2022-06-05 06:02 UTC, k9kathyli approved these changes

2022-06-05 23:35 UTC, Dsuzuki126 approved these changes
Doesn't look like any of the files changed for me. 
All the tests passed as well.

- [x] Straightforward implementation
- [x] Good design
- [x] Code looks correct
- [ ] UI looks as intended and fits guidelines
- [ ] Adequate test coverage
- [ ] Follows coding conventions
- [ ] Code is commented/documented well

2022-06-06 00:42 UTC, ManitKSoni approved these changes
- [x] Straightforward implementation
- [ ] Good design
- [ ] Code looks correct
- [ ] UI looks as intended and fits guidelines
- [ ] Adequate test coverage
- [x] Follows coding conventions
- [x] Code is commented/documented well

2022-06-06 01:10 UTC, Dsuzuki126 approved these changes
Nice job fixing the double error thing
- [ ] Straightforward implementation
- [ ] Good design
- [ ] Code looks correct
- [ ] UI looks as intended and fits guidelines
- [ ] Adequate test coverage
- [ ] Follows coding conventions
- [ ] Code is commented/documented well

2022-06-06 01:12 UTC, merged