Alejandro hitting enter for login 55
CSE112-SP22-TeamXRefactor/CSE112-SP22-TeamXRefactor pull request #77
Opened 2022-06-01 15:43 UTC by AlejandroM2000

![Screen Shot 2022-06-01 at 8 42 16 AM](https://user-images.githubusercontent.com/50216497/171445012-498d2526-959e-48b7-8a2e-1625ab572f4c.png)

2022-06-01 19:45 UTC, Hunter27E requested changes
- [x] Straightforward implementation
- [x] Good design
- [x] Code looks correct
- [x] UI looks as intended and fits guidelines
- [x] Adequate test coverage
- [x] Follows coding conventions
- [  ] Code is commented/documented well

One small change - remove the comment found at source/Login/LoginJS.js:16.

2022-06-01 20:01 UTC, Hunter27E approved these changes
- [x] Straightforward implementation
- [x] Good design
- [x] Code looks correct
- [x] UI looks as intended and fits guidelines
- [x] Adequate test coverage
- [x] Follows coding conventions
- [x] Code is commented/documented well

2022-06-02 00:54 UTC, k9kathyli reviewed
- [x] Straightforward implementation
- [x] Good design
- [x] Code looks correct
- [x] UI looks as intended and fits guidelines
- [x] Adequate test coverage
- [x]  Follows coding conventions
- [x] Code is commented/documented well

2022-06-02 00:54 UTC, k9kathyli approved these changes

2022-06-02 00:59 UTC, merged